### ISSUE TITLE
Bad measurements using Teensy 4.0 & 4.1 example

### ISSUE THREAD

**Issue by samsterckval** [PaulStoffregen/FreqCount#23]
### Description

Running the provided examples for Teensy 4.0, on both Teensy 4.0 & Teensy 4.1 gives bad measurements, ranging from 20-ish MHz to 60-ish MHz

### Steps To Reproduce Problem

 - Download lib
 - Copy files to lib/ to use with PlatformIO
 - Place jumper between pin 8 & pin 9
 - Flash Teensy4.x board
 - Run T4 example with standard 600MHz
 - Read from Serial

### Hardware & Software

Board :  Teensy4.0 & Teensy4.1
Shields / modules used : None
Arduino IDE version : PlatformIO
Teensyduino version (if using Teensy) : PlatformIO
Version info & package name (from Tools > Boards > Board Manager)
Operating system & version : MacOS 10.15
Any other software or hardware? PlatformIO

### Arduino Sketch

```cpp
/* FreqCount - Example with serial output
 * http://www.pjrc.com/teensy/td_libs_FreqCount.html
 *
 * This example code is in the public domain.
 *
 * For the Teensy 4.0 pin 9 is used to measure the freq
 * FreqCount.begin time is in microseconds vs milliseconds
 * for other boards.
 * As a test the sketch is setup to output 50Mhz on pin 11 sopen
 * add a jumper from pin 8 to pin 9.
 */
#include <FreqCount.h>

void setup() {
  Serial.begin(57600);
  
  delay(2000);
  analogWriteFrequency(8, 50000000);  // test jumper 11 to 25
  analogWrite(8, 128);
  
  FreqCount.begin(1000000);  //Time in microseconds
}

void loop() {
  if (FreqCount.available()) {
    unsigned long count = FreqCount.read();
    Serial.println(count);
  }
}
```

### Errors or Incorrect Output

Incorrect Output : 

25411440
25412338
25551684
25261721
25628678
25596966
25463273
25498595
25421364
25102215
24389548
21364609
17707919
38600278
28360883
16560541
25160703
25480417
25660020
25734367

**Comment by samsterckval** [comment]
This issue is due to bad signal conditioning, and is fixed by using a .1" jumper on the teensy directly instead of a jumper wire.

**Comment by PaulStoffregen** [comment]
glad you found the problem
